In [36]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

from combine_features import read_data

In [56]:
df = read_data("../rhea-soil-nutrient-prediction-challenge/Train.csv")
df.head()

,ID,Longitude,Latitude,Depth_cm,ph,Area,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area,tmin_avg,...,Cu,Fe,Mg,Mn,N,P,K,Na,S,Zn
0,BF9XTB,37.65189,-3.15440,20-50,6.405,Kenya,14.202173,3.902236,-7.263155,15.240530,...,5.826,81.780,306.836,270.240,0.79,NaN,300.951,NaN,NaN,NaN
1,2RWYTR,37.63612,-3.08585,20-50,6.419,Kenya,14.202173,3.902236,-7.263155,15.240530,...,4.346,97.198,407.980,185.557,1.11,NaN,292.696,NaN,NaN,NaN
2,XZI9Q6,39.55580,-2.67218,20-50,8.388,Kenya,14.202173,3.902236,-7.263155,21.969696,...,3.657,42.672,1256.319,178.299,0.45,NaN,814.911,NaN,NaN,NaN
3,4CBCVY,39.55477,-2.67196,20-50,8.302,Kenya,14.202173,3.902236,-7.263155,21.969696,...,3.376,52.861,1322.732,464.137,0.31,NaN,815.337,NaN,NaN,NaN
4,F9GK9S,39.55477,-2.67196,20-50,8.292,Kenya,14.202173,3.902236,-7.263155,21.969696,...,3.351,46.057,1134.898,274.565,0.45,NaN,928.238,NaN,NaN,NaN

In [57]:
encoder = LabelEncoder()
df['Depth'] = encoder.fit_transform(df['Depth_cm'])
# df.drop(columns=['ID', 'Area', 'Depth_cm'], inplace=True)
# df.dropna(axis=1, thresh=int(0.8 * df.shape[0]), inplace=True) # drops target columns :(
# df.dropna(axis=0, inplace=True)
df.head()

,ID,Longitude,Latitude,Depth_cm,ph,Area,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area,tmin_avg,...,Fe,Mg,Mn,N,P,K,Na,S,Zn,Depth
0,BF9XTB,37.65189,-3.15440,20-50,6.405,Kenya,14.202173,3.902236,-7.263155,15.240530,...,81.780,306.836,270.240,0.79,NaN,300.951,NaN,NaN,NaN,1
1,2RWYTR,37.63612,-3.08585,20-50,6.419,Kenya,14.202173,3.902236,-7.263155,15.240530,...,97.198,407.980,185.557,1.11,NaN,292.696,NaN,NaN,NaN,1
2,XZI9Q6,39.55580,-2.67218,20-50,8.388,Kenya,14.202173,3.902236,-7.263155,21.969696,...,42.672,1256.319,178.299,0.45,NaN,814.911,NaN,NaN,NaN,1
3,4CBCVY,39.55477,-2.67196,20-50,8.302,Kenya,14.202173,3.902236,-7.263155,21.969696,...,52.861,1322.732,464.137,0.31,NaN,815.337,NaN,NaN,NaN,1
4,F9GK9S,39.55477,-2.67196,20-50,8.292,Kenya,14.202173,3.902236,-7.263155,21.969696,...,46.057,1134.898,274.565,0.45,NaN,928.238,NaN,NaN,NaN,1

In [30]:
target = [
        "Al",
        "B",
        "Ca",
        "C_organic",
        "C_total",
        "Cu",
        "Fe",
        "Mg",
        "Mn",
        "N",
        "P",
        "K",
        "Na",
        "S",
        "Zn",
    ]
x = df.drop(columns=target, errors='ignore')
y_columns = df.columns.difference(x.columns)
y = df[y_columns]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [31]:
x_train.head()

,Longitude,Latitude,ph,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area,tmin_avg,tmax_avg,prec_avg,Bananas,...,Rice,"Seed cotton, unginned",Sesame seed,Sorghum,Soya beans,Sugar cane,Sweet potatoes,Tomatoes,Unmanufactured tobacco,Depth
6489,42.73327,9.63641,8.360,12.434945,-0.612673,-4.526182,11.579545,26.409090,63.800938,8114.509091,...,2562.272727,1116.518182,781.409091,2242.354545,2469.618182,40162.590909,27029.100000,9034.509091,675.527273,0
11881,48.70980,-18.27420,4.862,5.251518,-1.973700,-2.899782,15.196970,25.528410,127.234060,5508.127273,...,3291.472727,980.354545,0.000000,566.727273,593.090909,31748.763636,7640.372727,8651.509091,783.772727,0
8746,26.51750,-21.79080,7.003,56.498218,2.144745,7.334409,13.214015,29.979166,32.133892,0.000000,...,0.000000,2467.000000,0.000000,473.781818,0.000000,0.000000,11428.600000,44759.450000,0.000000,1
8775,26.52350,-21.77120,8.409,56.498218,2.144745,7.334409,13.214015,29.979166,32.133892,0.000000,...,0.000000,2467.000000,0.000000,473.781818,0.000000,0.000000,11428.600000,44759.450000,0.000000,1
11156,35.28978,-22.85395,6.318,9.193700,-1.378309,-7.520327,17.833334,30.005682,70.289390,7727.145455,...,532.990909,554.981818,623.954545,503.063636,1355.866667,69430.263636,9185.563636,18506.954545,1157.872727,0

In [32]:
y_train.head()

,Al,C_organic,C_total,Ca,Cu,Fe,K,Mg,Mn,N
6489,308.492,24.92,37.41,13740.489,4.572,35.494,530.812,1033.363,127.708,1.37
11881,1142.784,42.07,42.65,323.494,2.271,192.366,67.531,96.545,102.805,3.25
8746,684.280,22.35,26.94,3938.085,5.797,105.015,1029.506,1604.786,171.618,1.93
8775,298.667,14.50,22.31,11769.776,5.077,117.038,896.004,722.193,71.026,1.70
11156,510.097,6.25,6.63,638.328,0.566,62.306,47.994,88.265,101.614,0.50

In [50]:
rfr = RandomForestRegressor(n_estimators=100, random_state=42)
rfr.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [51]:
y_pred = rfr.predict(x_test)

In [52]:
rmse = root_mean_squared_error(y_test, y_pred, multioutput='raw_values')

pd.DataFrame(rmse, index=y_test.columns, columns=['RMSE'])

                 RMSE
Al         130.629088
C_organic    4.702238
C_total      4.874987
Ca         897.688839
Cu           0.774523
Fe          26.580686
K           98.042506
Mg         144.064590
Mn          41.987929
N            0.421565

In [53]:
fi = pd.DataFrame(rfr.feature_importances_, index=x_train.columns, columns=['Feature Importance'])
fi.sort_values(by='Feature Importance', ascending=False)

                                                    Feature Importance
ph                                                            0.697721
Longitude                                                     0.172341
Latitude                                                      0.045673
Other fruits, n.e.c.                                          0.028884
Groundnuts, excluding shelled                                 0.022275
tmax_avg                                                      0.008348
prec_avg                                                      0.007490
tmin_avg                                                      0.006029
Depth                                                         0.003504
Other pulses n.e.c.                                           0.001476
Soya beans                                                    0.000647
Unmanufactured tobacco                                        0.000534
Oranges                                                       0.000520
Onions and shallots, dry (excluding dehydrated)               0.000409
Cropland nitrogen per unit area                               0.000392
Maize (corn)                                                  0.000392
Other vegetables, fresh n.e.c.                                0.000359
Cropland phosphorus per unit area                             0.000315
Cropland potassium per unit area                              0.000231
Sesame seed                                                   0.000230
Tomatoes                                                      0.000216
Sweet potatoes                                                0.000203
Sorghum                                                       0.000199
Potatoes                                                      0.000188
Mangoes, guavas and mangosteens                               0.000176
Coffee, green                                                 0.000160
Beans, dry                                                    0.000159
Millet                                                        0.000156
Bananas                                                       0.000137
Seed cotton, unginned                                         0.000135
Pineapples                                                    0.000106
Sugar cane                                                    0.000103
Cashew nuts, in shell                                         0.000081
Cassava, fresh                                                0.000073
Rice                                                          0.000071
Chillies and peppers, green (Capsicum spp. and ...            0.000065