In [2]:
import pandas as pd
import numpy as np

In [13]:
faostat = pd.read_csv('../datasets/faostat_crops_and_livestock.csv')
faostat.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,24,Angola,5312,Area harvested,01311,Avocados,2014,2014,ha,NaN,M,Missing value; data cannot exist,NaN
1,QCL,Crops and livestock products,24,Angola,5510,Production,01311,Avocados,2014,2014,t,NaN,M,Missing value; data cannot exist,NaN
2,QCL,Crops and livestock products,24,Angola,5312,Area harvested,01311,Avocados,2015,2015,ha,5914.0,A,Official figure,NaN
3,QCL,Crops and livestock products,24,Angola,5412,Yield,01311,Avocados,2015,2015,kg/ha,12087.4,A,Official figure,NaN
4,QCL,Crops and livestock products,24,Angola,5510,Production,01311,Avocados,2015,2015,t,71485.0,A,Official figure,NaN

In [14]:
faostat = faostat.drop(columns=['Domain Code', 'Area Code (M49)', 'Element Code', 'Item Code (CPC)', 'Year Code', 'Note', 'Flag', 'Flag Description'])
faostat = faostat.drop(columns=['Domain'])
faostat.head()

     Area         Element      Item  Year   Unit    Value
0  Angola  Area harvested  Avocados  2014     ha      NaN
1  Angola      Production  Avocados  2014      t      NaN
2  Angola  Area harvested  Avocados  2015     ha   5914.0
3  Angola           Yield  Avocados  2015  kg/ha  12087.4
4  Angola      Production  Avocados  2015      t  71485.0

In [15]:
print(faostat['Element'].unique())

['Area harvested' 'Production' 'Yield']

In [16]:
faostat = faostat[faostat['Element'] == 'Yield']
faostat = faostat.drop(columns=['Element', 'Unit'])
faostat = faostat.rename(columns={'Value': 'Yield'})
faostat.head()

      Area      Item  Year    Yield
3   Angola  Avocados  2015  12087.4
6   Angola  Avocados  2016  12328.1
9   Angola  Avocados  2017  12249.0
12  Angola  Avocados  2018  11925.5
15  Angola   Bananas  2008  17981.6

In [17]:
print(faostat['Area'].unique())

['Angola' 'Botswana' 'Burkina Faso' 'Cameroon' "Côte d'Ivoire" 'Ethiopia'
 'Ghana' 'Guinea' 'Kenya' 'Madagascar' 'Malawi' 'Mali' 'Mozambique'
 'Niger']

In [6]:
olek_features = pd.read_csv('../features/olek-features.csv')
olek_features.head()

,ID,Country,Area,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area
0,O2TONM,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
1,BQLUK6,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
2,LSET8M,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
3,LEEL7I,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
4,LDNGO2,Tanzania,Tanzania,6.777309,-2.492418,-7.380091

In [7]:
print(olek_features['Area'].unique())

['Tanzania' 'Kenya' 'Uganda' 'Ethiopia' 'Cameroon' 'Ghana' 'Nigeria'
 "Côte d'Ivoire" 'Guinea' 'Burkina Faso' 'Mali' 'Niger' 'South Africa'
 'Mozambique' 'Botswana' 'Zimbabwe' 'Madagascar' 'Angola' 'Zambia'
 'Malawi']

In [ ]:
pivot = faostat.pivot_table(index='Area', columns=['Item'], values='Yield', aggfunc='mean').reset_index()
pivot.head()

Item,Area,"Abaca, manila hemp, raw","Almonds, in shell","Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw",Apples,Apricots,Artichokes,Asparagus,Avocados,"Bambara beans, dry",...,Tea leaves,Tomatoes,Tung nuts,Unmanufactured tobacco,"Vanilla, raw",Vetches,"Walnuts, in shell",Watermelons,Wheat,Yams
0,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12147.500000,NaN,...,NaN,10544.109091,NaN,1018.445455,NaN,NaN,NaN,NaN,1001.118182,NaN
1,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,44759.450000,NaN,NaN,NaN,NaN,NaN,98466.750000,1065.950000,NaN
2,Burkina Faso,NaN,549.372727,NaN,NaN,NaN,NaN,NaN,NaN,1097.027273,...,NaN,17100.609091,NaN,734.236364,NaN,NaN,1498.816667,NaN,NaN,6842.890909
3,Cameroon,NaN,NaN,NaN,NaN,5053.609091,NaN,NaN,4345.527273,907.254545,...,10602.509091,12658.981818,NaN,1503.327273,NaN,NaN,NaN,24009.654545,1332.436364,10493.690909
4,Côte d'Ivoire,NaN,589.263636,NaN,NaN,NaN,NaN,NaN,6521.063636,NaN,...,NaN,10221.927273,NaN,514.263636,NaN,NaN,NaN,NaN,NaN,6403.400000

In [25]:
pivot = pivot.dropna(axis=1, thresh=10)
pivot = pivot.fillna(0)
pivot.head()

Item,Area,Bananas,"Beans, dry","Cashew nuts, in shell","Cassava, fresh","Chillies and peppers, green (Capsicum spp. and Pimenta spp.)","Coffee, green","Groundnuts, excluding shelled",Maize (corn),"Mangoes, guavas and mangosteens",...,Potatoes,Rice,"Seed cotton, unginned",Sesame seed,Sorghum,Soya beans,Sugar cane,Sweet potatoes,Tomatoes,Unmanufactured tobacco
0,Angola,24064.809091,405.136364,690.927273,11559.654545,0.000000,296.436364,560.190909,883.545455,11381.525000,...,7324.909091,1022.400000,1446.963636,263.136364,227.736364,603.709091,38876.818182,8256.936364,10544.109091,1018.445455
1,Botswana,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,446.145455,227.227273,0.000000,...,15454.050000,0.000000,2467.000000,0.000000,473.781818,0.000000,0.000000,11428.600000,44759.450000,0.000000
2,Burkina Faso,25250.216667,0.000000,892.290909,15187.918182,4513.727273,0.000000,799.118182,1679.145455,8623.972727,...,1926.981818,2197.463636,1193.318182,619.800000,982.563636,1300.981818,101775.372727,11356.209091,17100.609091,734.236364
3,Cameroon,15425.472727,1281.181818,0.000000,13845.209091,2126.245455,391.063636,1346.954545,1894.672727,5743.236364,...,9527.363636,1642.600000,1374.945455,919.781818,1467.390909,1257.536364,39950.227273,5891.345455,12658.981818,1503.327273
4,Côte d'Ivoire,43863.081818,855.745455,413.827273,6537.800000,6431.863636,169.409091,1273.509091,2054.745455,560.509091,...,0.000000,2448.181818,1035.763636,198.981818,679.290909,1305.281818,76121.318182,1904.236364,10221.927273,514.263636

In [26]:
pivot.to_csv('../features/mateusz-features.csv', index=False)